name: Deploy Streamlit App to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # This is the environment we'll use

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Make sure this is compatible with your app

    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Cloud
      run: |
        # Add any steps for deployment (if needed)
        echo "Deployment step (if needed)"
